function extractDollar(regex, text) {
  const match = text.match(regex);
  if (!match) return null;
  return Number(match[1].replace(/,/g, ''));
}

// Parses the fields we need out of the "Daily Cash Report" Slack message.
// The report is generated by another system and its wording can drift, so
// every field is best-effort: a field that fails to match comes back as
// `null` rather than throwing, and the caller decides how to degrade.
function parseCashReport(text) {
  const weekToDate =
    extractDollar(/\$([\d,]+)\s+on the board/i, text) ??
    extractDollar(/new week starts today:\s*\$([\d,]+)/i, text);

  const lastWeekMatch = text.match(/Last week \(([^)]+)\) closed at \$([\d,]+)/i);

  const monthToDateNew = extractDollar(/New cash collected this month:\s*\$([\d,]+)/i, text);
  const monthToDateRecurring = extractDollar(/Recurring collected this month:\s*\$([\d,]+)/i, text);

  return {
    weekToDate,
    lastWeekTotal: lastWeekMatch ? Number(lastWeekMatch[2].replace(/,/g, '')) : null,
    lastWeekRange: lastWeekMatch ? lastWeekMatch[1] : null,
    monthToDateNew,
    monthToDateRecurring,
    raw: text,
  };
}

module.exports = { parseCashReport };
